SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
# player movement physics
PLAYER_ACCELERATION = 400.0  # pixels per second^2
PLAYER_MAX_SPEED = 300.0     # pixels per second
PLAYER_DRAG = 0.8            # linear drag factor per second (fraction removed per second)

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5
SHOT_LIFETIME_SECONDS = 5.0
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_LIVES = 3

# explosion visuals
EXPLOSION_MAX_RADIUS = 60
EXPLOSION_DURATION = 0.6